version: '3'

services:
  mysql-dev:
    container_name: mysql-dev
    image: mysql:8.0
    ports:
      - "32768:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: public
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
